export const TOGGLE_IS_AUTHENTICATED = 'toggleIsAuthenticated'
export const TOGGLE_MODAL_AUTH = 'toggleModalAuth'
export const TOGGLE_MODAL_AUTH_ACTIVE_CARD = 'toggleModalAuthActiveCard'
export const TOGGLE_MODAL_LOST_PWD = 'toggleModalLostPwd'
export const TOGGLE_MODAL_IDENTITY = 'toggleModalIdentity'
